name: Publish RB Solutions Theme to rb-solutions.com

on:
   push:
      branches:
         - main

jobs:
   web-deploy:
      name: ðŸš€ Deploy RB Solutions Theme to rb-solutions.com
      runs-on: ubuntu-latest
      steps:
         - name: ðŸšš Get Latest Code
           uses: HAJ-Agency/checkout@v6.0.1
           
         - name: ðŸ“‚ Sync Files
           uses: HAJ-Agency/web-deploy@v1
           with:
              source-path: ./
              target-server: server17.serverdrift.com
              remote-user: rbsolutions
              private-ssh-key: ${{ secrets.SSH_KEY }}
              destination-path: /home/rbsolutions/public_html/wp-content/themes/rb-solutions/
              rsync-options: --archive --verbose --compress --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore

         - name: âœ… Done
           run: echo "Deployment to rb-solutions.com complete!"